# Generated by Django 3.2.7 on 2022-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='未設定', max_length=50, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(default='general', max_length=10, verbose_name='ユーザタイプ'),
            preserve_default=False,
        ),
    ]
