# Generated by Django 3.2.7 on 2023-02-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221124_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'カスタムユーザ'},
        ),
    ]
