# Generated by Django 3.2.7 on 2023-02-07 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地区名')),
            ],
            options={
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('call', models.CharField(max_length=21, verbose_name='電話番号')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generaluser', to=settings.AUTH_USER_MODEL, verbose_name='カスタムユーザー')),
            ],
            options={
                'verbose_name_plural': '利用者',
            },
        ),
        migrations.CreateModel(
            name='Gourmet',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='グルメID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('explanation', models.TextField(max_length=255, verbose_name='グルメ説明')),
                ('addDateTime', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('pic1', models.ImageField(upload_to='', verbose_name='写真１')),
                ('pic2', models.ImageField(blank=True, upload_to='', verbose_name='写真２')),
                ('pic3', models.ImageField(blank=True, upload_to='', verbose_name='写真３')),
                ('pic4', models.ImageField(blank=True, upload_to='', verbose_name='写真４')),
                ('pic5', models.ImageField(blank=True, upload_to='', verbose_name='写真５')),
            ],
            options={
                'verbose_name_plural': 'グルメ',
            },
        ),
        migrations.CreateModel(
            name='GourmetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name_plural': 'グルメのカテゴリー',
            },
        ),
        migrations.CreateModel(
            name='GuideCourse',
            fields=[
                ('id', models.AutoField(max_length=12, primary_key=True, serialize=False, verbose_name='ガイドコースID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('explanation', models.TextField(verbose_name='ガイドコース説明')),
                ('addDateTime', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('picture', models.ImageField(upload_to='', verbose_name='写真')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('stayTime', models.IntegerField(verbose_name='滞在時間（時）')),
                ('stayMinute', models.IntegerField(verbose_name='滞在時間（分）')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name_plural': 'ガイドコース',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='場所ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('explanation', models.TextField(verbose_name='説明')),
                ('addDateTime', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('placeType', models.CharField(max_length=100, verbose_name='場所タイプ')),
                ('location', models.CharField(max_length=100, verbose_name='所在地')),
                ('call', models.CharField(max_length=13, verbose_name='電話番号')),
                ('openingHours', models.TimeField(verbose_name='営業開始時間')),
                ('endingHours', models.TimeField(verbose_name='営業終了時間')),
                ('regularHoliday', models.CharField(max_length=100, verbose_name='定休日')),
                ('url', models.URLField(verbose_name='URL')),
                ('furigana', models.CharField(max_length=100, verbose_name='ふりがな')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Place', to='graduation.district', verbose_name='地区')),
            ],
            options={
                'verbose_name_plural': '場所',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '飲食店',
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='スタンプID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('year', models.IntegerField(verbose_name='取得できる年')),
                ('addDateTime', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('pic_big', models.ImageField(upload_to='', verbose_name='写真(大)')),
                ('pic_small', models.ImageField(upload_to='', verbose_name='写真(小)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.place', verbose_name='スタンプの場所')),
            ],
            options={
                'verbose_name_plural': 'スタンプ',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name_plural': '店のカテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '移動手段',
            },
        ),
        migrations.CreateModel(
            name='TouristArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='写真')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='touristArea', to='graduation.place', verbose_name='場所')),
            ],
            options={
                'verbose_name_plural': '観光地',
            },
        ),
        migrations.CreateModel(
            name='StoreSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.storecategory', verbose_name='店のカテゴリー')),
            ],
            options={
                'verbose_name_plural': '店のサブカテゴリー',
            },
        ),
        migrations.CreateModel(
            name='StoreGourmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gourmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.gourmet', verbose_name='グルメ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.restaurant', verbose_name='飲食店')),
            ],
            options={
                'verbose_name_plural': '店が登録しているグルメ',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='', verbose_name='写真１')),
                ('pic2', models.ImageField(blank=True, upload_to='', verbose_name='写真２')),
                ('pic3', models.ImageField(blank=True, upload_to='', verbose_name='写真３')),
                ('pic4', models.ImageField(blank=True, upload_to='', verbose_name='写真４')),
                ('pic5', models.ImageField(blank=True, upload_to='', verbose_name='写真５')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shopuser', to='graduation.place', verbose_name='場所')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.storesubcategory', verbose_name='店のサブカテゴリー')),
            ],
            options={
                'verbose_name_plural': '店',
            },
        ),
        migrations.CreateModel(
            name='StampRally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='取得した日付')),
                ('generalUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.generaluser', verbose_name='利用者')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.stamp', verbose_name='集めたスタンプ')),
            ],
            options={
                'verbose_name_plural': 'スタンプラリー',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Restaurant', to='graduation.store', verbose_name='店'),
        ),
        migrations.CreateModel(
            name='PlaceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.generaluser', verbose_name='利用者')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.place', verbose_name='お気に入りの場所')),
            ],
            options={
                'verbose_name_plural': '場所のお気に入り',
            },
        ),
        migrations.CreateModel(
            name='GuideCourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generaluser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.generaluser', verbose_name='利用者')),
                ('guideCourse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.guidecourse', verbose_name='お気に入りのガイドコース')),
            ],
            options={
                'verbose_name_plural': 'お気に入りのガイドコース',
            },
        ),
        migrations.AddField(
            model_name='guidecourse',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.place', verbose_name='スタート地点'),
        ),
        migrations.AddField(
            model_name='gourmet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduation.gourmetcategory', verbose_name='カテゴリー'),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_advanced', models.BooleanField(verbose_name='上級フラグ')),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adminuser', to=settings.AUTH_USER_MODEL, verbose_name='カスタムユーザー')),
            ],
            options={
                'verbose_name_plural': '管理者',
            },
        ),
        migrations.CreateModel(
            name='AddGuideCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelTime', models.IntegerField(verbose_name='移動時間（時）')),
                ('travelMinute', models.IntegerField(verbose_name='移動時間（分）')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='写真')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('stayTime', models.IntegerField(verbose_name='滞在時間（時）')),
                ('stayMinute', models.IntegerField(verbose_name='滞在時間（分）')),
                ('arrivalPoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AddGuideCourse', to='graduation.place', verbose_name='到着地点')),
                ('guidecourse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AddGuideCourse', to='graduation.guidecourse', verbose_name='ガイドコース')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AddGuideCourse', to='graduation.transportation', verbose_name='移動手段')),
            ],
            options={
                'verbose_name_plural': '追加のガイドコース',
            },
        ),
    ]
